apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-local-path
provisioner: rancher.io/local-path
parameters:
  path: "/data/tufin-assignment"
volumeBindingMode: WaitForFirstConsumer
