mysql:
  image: mysql:5.7
  rootPassword: rootpassword
  database: wordpress
  user: wordpress
  password: wordpresspassword

wordpress:
  image: wordpress:latest
  dbHost: mysql
  dbPort: 3306
  dbUser: wordpress
  dbPassword: wordpresspassword
  dbName: wordpress
