apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Mysql.Image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Mysql.RootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Mysql.Database }}
        - name: MYSQL_USER
          value: {{ .Mysql.User }}
        - name: MYSQL_PASSWORD
          value: {{ .Mysql.Password }}
