apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: rancher.io/local-path
parameters:
  path: {{ .Values.storageClass.path }}
volumeBindingMode: WaitForFirstConsumer
