apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.configMap.name }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
  MYSQL_DATABASE: {{ .Values.mysql.database }}
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_PASSWORD: {{ .Values.mysql.password }}
  MYSQL_PORT: '{{ .Values.mysql.port }}'
