apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          envFrom:
            - configMapRef:
                name: {{ .Values.mysql.configMap.name }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  annotations:
    # This ensures compatibility with K3s's built-in service-lb
    service.beta.kubernetes.io/k3s-external-ip: {{ .Values.wordpress.externalIP | default "" }}
spec:
  ports:
    - name: mysql
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
  selector:
    app: {{ .Values.mysql.name }}
