apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.wordpress.configMap.name }}
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.dbHost }}
  WORDPRESS_DB_PORT: '{{ .Values.wordpress.dbPort }}'
  WORDPRESS_DB_USER: {{ .Values.wordpress.dbUser }}
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.dbPassword }}
  WORDPRESS_DB_NAME: {{ .Values.wordpress.dbName }}
  WORDPRESS_PORT: '{{ .Values.wordpress.port }}'
